baseurl = "/"
title = "phdjsep"
theme = "hyde"
languageCode = "en-us"
copyright = "Sep Dadsetan"
disqusShortname = "phdjsep"
googleAnalytics = "UA-16280498-1"
enableEmoji = true
paginate = 5

[Params]
    custom_css = ["css/poole.css", "css/hyde.css", "css/social.css"]
    description = "Data & Stuff"
    github = "https://github.com/phdjsep"
    linkedin = "https://linkedin.com/in/sepdadsetan/"
    twitter = "https://twitter.com/phdjsep"
    facebook = "https://facebook.com/phdjsep"

[Permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/page/about/"
