baseurl = "/"
title = "footgolf collective"
theme = "hyde"
languageCode = "en-us"
copyright = "Sep Dadsetan"
disqusShortname = "footgolfcollective"
googleAnalytics = ""
enableEmoji = true
paginate = 5

[Params]
    custom_css = ["css/poole.css", "css/hyde.css", "css/social.css"]
    description = "Footgolf & Stuff"
    # github = "https://github.com/phdjsep"
    # linkedin = "https://linkedin.com/in/sepdadsetan/"
    # twitter = "https://twitter.com/phdjsep"
    # facebook = "https://facebook.com/phdjsep"

[Permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/page/about/"
